version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      - CORS_ORIGIN=${VITE_SERVER_URL}
      - SECRET=${BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - DATABASE_URL=file:${DATABASE_URL}

    volumes:
      - ./db/db-current:/app/db

    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    depends_on:
      - backend
    restart: unless-stopped



