version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
    environment:
      - CORS_ORIGIN=http://localhost:3000
      - SECRET={BETTER_AUTH_SECRET}
      - BETTER_AUTH_URL=${BETTER_AUTH_URL}
      - DATABASE_URL=file:./db/local.db

    volumes:
      - ./db-data:/app/apps/server/db

    ports:
      - "3001:3001"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
    environment:
      - VITE_SERVER_URL=${VITE_SERVER_URL}
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped



